# Generated by Django 3.1.2 on 2022-11-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('manufacturer', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('size', models.IntegerField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
